---

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  when: ansible_os_family in ['RedHat', 'Ubuntu', 'Debian']
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "main.yml"
      paths:
        - "vars"

- name: Install Checkmk from official repos
  block:

    - name: "Download check-mk installer"
      get_url:
        url: "{{ checkmk_repo_url }}"
        dest: "/opt/{{ checkmk_installer_name }}"

    - name: "Setting up check-mk repository"
      yum:
        name: "/opt/{{ checkmk_installer_name }}"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: "Setting up check-mk repository"
      apt:
        deb: "/opt/{{ checkmk_installer_name }}"
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

  tags:
    - install-check-mk-server


- name: Configure Checkmk
  block:

    - name: Check for existing OMD site
      stat: path=/opt/omd/sites/{{ checkmk_site_name }}
      register: omd_site

    - name: Create OMD site if not exists
      command: omd create {{ checkmk_site_name }}
      when: omd_site.stat.exists|bool == false

    - name: install python-passlib for htpasswd
      yum:
        name: python-passlib
        state: present

    - name: Change OMD site admin password
      htpasswd:
        path: /omd/sites/{{ checkmk_site_name }}/etc/htpasswd
        name: cmkadmin
        password: "{{ checkmk_cmkadmin_password }}"
      become: true
      become_user: "{{ checkmk_site_name }}"

    - name: Restart OMD site
      command: omd restart {{ checkmk_site_name }}
  tags:
    - install-check-mk-server
